---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
  - npm run build -- -prod # build app and prepare dist folder

# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 0162367411ec9c12d372be81709c906eb830cf2f
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true
